rockets/keppler_frontend/config/routes.rb
KepplerFrontend::Engine.routes.draw do
  get '/', to: 'app/frontend#index', as: :index
  root to: 'app/frontend#keppler', as: :keppler
  namespace :admin do
    scope :frontend, as: :frontend do
      resources :parameters do
        get '(page/:page)', action: :index, on: :collection, as: ''
        get '/clone', action: 'clone'
        post '/sort', action: :sort, on: :collection
        post '/upload', action: 'upload', as: 'upload'
        get '/download', action: 'download', as: 'download'
        get(
          '/reload',
          action: :reload,
          on: :collection,
        )
        delete(
          '/destroy_multiple',
          action: :destroy_multiple,
          on: :collection,
          as: :destroy_multiple
        )
      end

      resources :functions do
        get '(page/:page)', action: :index, on: :collection, as: ''
        get '/clone', action: 'clone'
        post '/sort', action: :sort, on: :collection
        post '/upload', action: 'upload', as: 'upload'
        get '/download', action: 'download', as: 'download'
        get '/editor', action: 'editor'
        post '/editor/save', action: 'editor_save'
        delete '/destroy_param/:param_id', action: :destroy_param, as: :destroy_param
        get(
          '/reload',
          action: :reload,
          on: :collection,
        )
        delete(
          '/destroy_multiple',
          action: :destroy_multiple,
          on: :collection,
          as: :destroy_multiple
        )
      end

      resources :callback_functions do
        get '(page/:page)', action: :index, on: :collection, as: ''
        get '/clone', action: 'clone'
        post '/sort', action: :sort, on: :collection
        post '/upload', action: 'upload', as: 'upload'
        get '/download', action: 'download', as: 'download'
        get '/editor', action: 'editor'
        post '/editor/save', action: 'editor_save'
        get(
          '/reload',
          action: :reload,
          on: :collection,
        )
        delete(
          '/destroy_multiple',
          action: :destroy_multiple,
          on: :collection,
          as: :destroy_multiple
        )
      end

      resources :partials do
        get '(page/:page)', action: :index, on: :collection, as: ''
        get '/clone', action: 'clone'
        post '/sort', action: :sort, on: :collection
        post '/upload', action: 'upload', as: 'upload'
        post '/editor/save', action: 'editor_save'
        get '/download', action: 'download', as: 'download'
        get(
          '/reload',
          action: :reload,
          on: :collection,
        )
        delete(
          '/destroy_multiple',
          action: :destroy_multiple,
          on: :collection,
          as: :destroy_multiple
        )
      end

      resources :themes do
        get '(page/:page)', action: :index, on: :collection, as: ''
        get '/clone', action: 'clone'
        post '/sort', action: :sort, on: :collection
        post '/upload', action: 'upload', as: 'upload'
        get '/download', action: 'download', as: 'download'
        get '/show_covers', action: 'show_covers', as: 'show_covers'
        get '/editor', action: 'editor'
        post '/editor/save', action: 'editor_save'
        get(
          '/reload',
          action: :reload,
          on: :collection,
        )
        delete(
          '/destroy_multiple',
          action: :destroy_multiple,
          on: :collection,
          as: :destroy_multiple
        )
      end

      get '/assets', to: 'multimedia#index', as: 'multimedia'
      post '/assets/upload', to: 'multimedia#upload', as: 'upload_multimedia'
      get '/assets/upload', to: 'multimedia#upload', as: 'show_upload_multimedia'
      delete '/assets/:search/:fileformat', to: 'multimedia#destroy', as: 'destroy_multimedia'
      get '/assets/:search/:fileformat', to: 'multimedia#destroy', as: 'show_destroy_multimedia'

      resources :views do
        delete '/destroy_callback/:view_callback_id', action: :destroy_callback, as: :destroy_callback
        get '(page/:page)', action: :index, on: :collection, as: ''
        get '/clone', action: 'clone'
        get '/editor', action: 'editor'
        post '/editor/save', action: 'editor_save'
        post '/live_editor/save', action: 'live_editor_save'
        post '/sort', action: :sort, on: :collection
        post '/select_theme_view/:theme_view', action: 'select_theme_view', as: :select_theme

        get(
          '/reload',
          action: :reload,
          on: :collection,
        )
        delete(
          '/destroy_multiple',
          action: :destroy_multiple,
          on: :collection,
          as: :destroy_multiple
        )
      end

    end
  end
end

rockets/keppler_frontend/app/views/keppler_frontend/admin/views/_description.html.haml
%aside.control-sidebar.control-sidebar-light
  .tab-content
    %p.control-sidebar-heading
      = @activities.empty? ? t('keppler.messages.no_events') : t("keppler.titles.history")
    %ul.timeline
      - @activities.each do |activity|
        - if activity.trackable_type.eql? "Session"
          %li
            = render partial: "public_activity/session/#{activity.key.split(".").second}", locals: { activity: activity, method: "id" }
        - else
          %li
            = render partial: "public_activity/layout/#{activity.key.split(".").second}", locals: { activity: activity, method: "id" }
.control-sidebar-bg

rockets/keppler_frontend/app/views/keppler_frontend/admin/views/_editor_assets.html.haml
%aside.control-sidebar.control-sidebar-light#assets-editor
  %a.aside-close#close-assets-editor
    .label.bg-gray
      X
  %ul.nav.nav-tabs
    %li.active
      %a{'aria-expanded': "true", "data-toggle" => "tab", :href => "#editor_tab_1"}
        %i.fa.fa-image
    %li
      %a{'aria-expanded': 'false', "data-toggle" => "tab", :href => "#editor_tab_2"}
        %i.fa.fa-film
    %li
      %a{'aria-expanded': 'false', "data-toggle" => "tab", :href => "#editor_tab_3"}
        %i.fa.fa-music
    %li
      %a{'aria-expanded': 'false', "data-toggle" => "tab", :href => "#editor_tab_4"}
        %i.fa.fa-text-height
  .tab-content.container-files.bg-gray
    #editor_tab_1.tab-pane.active
      - @files_list.each_with_index do |file, i|
        - if file[:folder].eql?("images")
          .box.box-solid
            .box-header.with-border{title: "#{file[:name]}"}
              .row
                .col-lg-12
                  %h4.box-title
                    %i.fa.fa-image
                    = truncate(file[:name], length: 30, omission: '...')
            .box-body.no-padding
              .back-file-xs
                .file-image{style:"background-image:url('#{file[:path]}')"}
            .box-body
              %span.box-title
                = file[:size]
                %button.btn.btn-default.pull-right{onclick: "copy('#{file[:id]}')"}
                  %input.hidden{id: "#{file[:id]}", value: "#{file[:path]}"}
                  %i.fa.fa-save
    #editor_tab_2.tab-pane
      - @files_list.each_with_index do |file, i|
        - if file[:folder].eql?("videos")
          .box.box-solid
            .box-header.with-border{title: "#{file[:name]}"}
              .row
                .col-lg-12
                  %h4.box-title
                    %i.fa.fa-film
                    = truncate(file[:name], length: 30, omission: '...')
            .box-body.no-padding
              .back-file-xs
                .center
                  %video{ controls: 'true'}
                    %source{ src:"#{file[:path]}", type:"video/#{file[:format]}" }
                    Su navegador no soporta contenido multimedia.
            .box-body
              %span.box-title
                = file[:size]
                %button.btn.btn-default.pull-right{onclick: "copy('#{file[:id]}')"}
                  %input.hidden{id: "#{file[:id]}", value: "#{file[:path]}"}
                  %i.fa.fa-save
    #editor_tab_3.tab-pane
      - @files_list.each_with_index do |file, i|
        - if file[:folder].eql?("audios")
          .box.box-solid
            .box-header.with-border{title: "#{file[:name]}"}
              .row
                .col-lg-12
                  %h4.box-title
                    %i.fa.fa-music
                    = truncate(file[:name], length: 30, omission: '...')
            .box-body.no-padding
              .back-file-xs
                .center
                  %audio#aside-audio{controls: true}
                    %source{ src:"#{file[:path]}", type:"audio/#{file[:format]}" }
                    Your browser does not support the audio tag.
            .box-body
              %span.box-title
                = file[:size]
                %button.btn.btn-default.pull-right{onclick: "copy('#{file[:id]}')"}
                  %input.hidden{id: "#{file[:id]}", value: "#{file[:path]}"}
                  %i.fa.fa-save
    #editor_tab_4.tab-pane
      - @files_list.each_with_index do |file, i|
        - if file[:folder].eql?("fonts")
          .box.box-solid
            .box-header.with-border{title: "#{file[:name]}"}
              .row
                .col-lg-12
                  %h4.box-title
                    %i.fa.fa-text-height
                    = truncate(file[:name], length: 30, omission: '...')
            .box-body.no-padding
              .back-file-xs
                .center
                  %i.fa.fa-text-height#font-icon-size
            .box-body
              %span.box-title
                = file[:size]
                %button.btn.btn-default.pull-right{onclick: "copy('#{file[:id]}')"}
                  %input.hidden{id: "#{file[:id]}", value: "#{file[:path]}"}
                  %i.fa.fa-save
.control-sidebar-bg
:javascript
  $('a[data-toggle="tab"]').on('shown.bs.tab', function (ev) {
    var tab = ev.target.innerText;
    var id = `#{@view.id}`;

    if (tab === '') {
      tab = `#{@view.name}.html.erb`
    }

    $(document).bind('keydown', function(e) {
      if(e.ctrlKey && (e.which == 83)) {
        e.preventDefault();
        save()
      }
    });

    function save() {
      if ( tab === `#{@view.name}.html.erb` ) {
        codeHTML.save(id);
      } else if (tab === `#{@view.name}.scss` ) {
        codeCSS.save(id);
      } else if (tab === `#{@view.name}.js` ) {
        codeJs.save(id);
      } else if (tab === 'Action') {
        codeAction.save(id);
      }
    }
  })

rockets/keppler_frontend/app/views/keppler_frontend/admin/views/_editor_themes.html.haml
%aside.control-sidebar.control-sidebar-light#theme-editor
  %a.aside-close#close-theme-editor
    .label.bg-gray
      X
  %ul.nav.nav-tabs
    %li.active
      %a{'aria-expanded': 'false', "data-toggle" => "tab", :href => "#editor_theme_tab_2"}
        %i.fa.fa-tint
  .tab-content.container-files.bg-gray
    #editor_theme_tab_2.tab-pane.active
      - @files_views.each_with_index do |file, i|
        .box.box-solid
          .box-header.with-border{title: "#{file[:name]}"}
            .row
              .col-lg-12
                %h4.box-title
                  %i.fa.fa-tint
                  = truncate(file[:name].split('.').first, length: 30, omission: '...')
          .box-body.no-padding
            .back-file-xs
              .center
                - if file[:cover].nil?
                  %i.fa.fa-tint#font-icon-size
                - else
                  = image_tag file[:cover]
          .box-body
            %span.box-title
              = file[:size]
              = link_to admin_frontend_view_select_theme_path(@view, file[:name]), class: 'btn btn-default pull-right', method: :post, data: { confirm: t("keppler_frontend.select_view_confirm") } do
                %i.fa.fa-check
.control-sidebar-bg

:javascript
  $('a[data-toggle="tab"]').on('shown.bs.tab', function (ev) {
    var tab = ev.target.innerText;
    var id = `#{@view.id}`;

    if (tab === '') {
      tab = `#{@view.name}.html.erb`
    }

    $(document).bind('keydown', function(e) {
      if(e.ctrlKey && (e.which == 83)) {
        e.preventDefault();
        save()
      }
    });

    function save() {
      if ( tab === `#{@view.name}.html.erb` ) {
        codeHTML.save(id);
      } else if (tab === `#{@view.name}.scss` ) {
        codeCSS.save(id);
      } else if (tab === `#{@view.name}.js` ) {
        codeJs.save(id);
      } else if (tab === 'Action') {
        codeAction.save(id);
      }
    }
  })

rockets/keppler_frontend/app/views/keppler_frontend/admin/views/_editor_views.html.haml
%aside.control-sidebar.control-sidebar-light#views-editor
  %a.aside-close#close-views-editor
    .label.bg-gray
      X
  %ul.nav.nav-tabs
    %li.active
      %a{'aria-expanded': "true", "data-toggle" => "tab", :href => "#editor_views_tab_1"}
        %i.fa.fa-desktop
    %li
      %a{'aria-expanded': "true", "data-toggle" => "tab", :href => "#editor_views_tab_2"}
        %i.fa.fa-code
    %li
      %a{'aria-expanded': "true", "data-toggle" => "tab", :href => "#editor_views_tab_3"}
        %i.fa.fa-file
  .tab-content.container-files.bg-gray
    #editor_views_tab_1.tab-pane.active
      - @views.each do |view|
        .box.box-solid
          .box-header.with-border{title: "#{view.name}"}
            .row
              .col-lg-6
                %h4.box-title
                  %i.fa.fa-desktop
                  = truncate(view.name, length: 10, omission: '...')
              .col-lg-3
                %span.box-title
                  %a.btn.btn-default.pull-right{onclick: "copy('#{view.id}')"}
                    %input.hidden{id: "#{view.id}", value: "#{view.path}"}
                    %i.fa.fa-save
              .col-lg-2
                %span.box-title
                  = link_to view.route, class: 'btn btn-default pull-right', 'data-no-turbolink': true do
                    %i.fa.fa-reply
    #editor_views_tab_2.tab-pane
      - @functions.each do |function|
        .box.slice-box.collapsed-box
          .box-header.with-border
            %h3.box-title
              %i.fa.fa-code
              = function.name
            .box-tools.pull-right
              %a.btn.btn-box-tool{"data-widget" => "collapse", :type => "button"}
                %i.fa.fa-plus
          .box-body
            %p
              = function.description
            %hr
            %strong Parámetros:
            %br
            = function.parse_parameters
            %hr
            .col-lg-3
              %span.box-title
                %a.btn.btn-default.pull-right{onclick: "copy('#{function.id}')"}
                  %input.hidden{id: "#{function.id}", value: "#{function.name}(#{function.parse_parameters})"}
                  %i.fa.fa-save
            .col-lg-2
              %span.box-title
                = link_to admin_frontend_function_path(function.id), class: 'btn btn-default pull-right' do
                  %i.fa.fa-reply
    #editor_views_tab_3.tab-pane
      - @partials.each do |partial|
        .box.box-solid
          .box-header.with-border{title: "#{partial.name}"}
            .row
              .col-lg-6
                %h4.box-title
                  = truncate(partial.name, length: 30, omission: '...')
              .col-lg-3
                %span.box-title
                  %a.btn.btn-default.pull-right{onclick: "copyPartial('#{partial.id}')"}
                    %input.hidden{id: "partial#{partial.id}", value: "<%= #{partial.name} %>" }
                    %i.fa.fa-save
              .col-lg-2
                %span.box-title
                  = link_to admin_frontend_partial_path(partial), class: 'btn btn-default pull-right', target: '_blank' do
                    %i.fa.fa-reply
.control-sidebar-bg

:javascript
  $('a[data-toggle="tab"]').on('shown.bs.tab', function (ev) {
    $(document).bind('keydown',function(e) {
      if(e.ctrlKey && (e.which == 83)) {
        e.preventDefault();
        var tab = e.target.innerText;
        if (tab==='') {
          var tab = `#{@view.name}.html.erb`;
        }
        var id = `#{@view.id}`
        if ( tab === `#{@view.name}.html.erb`) {
          codeHTML.save(id);
        } else if (tab === `#{@view.name}.scss`) {
          codeCSS.save(id);
        } else if (tab === `#{@view.name}.js`) {
          codeJs.save(id);
        } else if (tab === 'Action') {
          codeAction.save(id);
        }
      }
    });
  })

rockets/keppler_frontend/app/views/keppler_frontend/admin/views/_form.html.haml
= simple_form_for [:admin, :frontend, @view] do |f|
  .container
    .row
      .col-lg-2
        = link_to admin_frontend_views_path, "data-position" => "bottom", "data-tooltip" => t("keppler.actions.back") do
          .arrow-back.btn.btn-default
            %i.fa.fa-angle-left
            = t('keppler.actions.back')

    .row
      .col-lg-12
        .box.slice-box.p-15
          .box-header.with-border
            %h3.box-title= t("keppler.modules.#{action_name.underscore}")
          .box-body
            %table.table.table-bordered
              %tbody
                .form-padding
                  .row
                    .col-xs-3
                      = f.input :name
                    .col-xs-3
                      - if action_name.eql?('new')
                        = f.input :url, input_html: {value: '/'}
                      - else
                        = f.input :url
                    .col-xs-2
                      = f.input :method, collection: [:GET, :POST, :PATCH, :PUT, :DELETE], prompt: false
                    .col-xs-2
                      - if ['new', 'create'].include?(action_name)
                        = f.input :format_result, collection: [:HTML, :JS, :Action], prompt: false
                      - else
                        = f.input :format_result, collection: [:HTML, :JS, :Action], prompt: false, disabled: true
                    .col-xs-2
                      = f.input :active, as: :keppler_boolean
                    .col-xs-12
                      = f.input :position, as: :hidden
                    .col-xs-12
                      = f.input :deleted_at, as: :hidden
          .box-footer
            - if ['new', 'create'].include?(action_name)
              .pull-right
                = f.button :submit, t('keppler.actions.save'), name: '_save', class: 'btn-primary'
      - if action_name.eql?('edit') || action_name.eql?('update')
        .col-lg-12
          .box.slice-box.p-15
            .box-header.with-border
              %h3.box-title= t("keppler_frontend.form.callbacks")
              .box-body
                %table.table.table-bordered
                %tbody
                  .form-padding
                    .row
                      .col-xs-12
                        = f.simple_fields_for :view_callbacks do |view_callback|
                          - if view_callback.object.name
                            = render 'view_callback_fields_edit', f: view_callback
                          - else
                            = render 'view_callback_fields', f: view_callback
                        .links
                          = link_to_add_association "<button class='btn btn-default'> + #{t('keppler_frontend.actions.add_callback')}</button>".html_safe, f, :view_callbacks
                        %br
                        %br
              .box-footer
                .pull-right
                  = f.button :submit, t('keppler.actions.save'), name: '_save', class: 'btn-primary'

rockets/keppler_frontend/app/views/keppler_frontend/admin/views/_listing.html.haml
- objects.each do |view|
  %tr{ id: "row-#{view.id}" }
    %td.item-check{ style: 'width: 10%' }
      - if can?(KepplerFrontend::View).destroy_multiple?
        .checkbox
          %label{ for: "checkbox-#{view.id}" }
            %input{ type: 'checkbox', id: "checkbox-#{view.id}", 'checklist-model' => 'check', 'checklist-value' => "#{view.id}", '@click' => "listDelete(#{view.id})"}
            %span.cr
              %i.cr-icon.glyphicon.glyphicon-ok

    %td
      = link_to admin_frontend_view_editor_path(view), class: 'new-menu', title: t('keppler.actions.edit') do
        %span
          .label{class: "bg-#{view.color}"}
            = view.method
    %td
      = link_to admin_frontend_view_editor_path(view), class: 'new-menu', title: t('keppler.actions.edit') do
        %span
          = view.name
    %td
      = link_to admin_frontend_view_editor_path(view), class: 'new-menu', title: t('keppler.actions.edit') do
        %span
          = view.url
    %td.hidden-xs.hidden-sm
      = link_to admin_frontend_view_editor_path(view), class: 'new-menu', title: t('keppler.actions.edit') do
        %span
          .label{class: "bg-#{view.active ? 'green' : 'gray'}"}
            = view.active.to_s.capitalize
    %td.hidden-xs.hidden-sm
      = link_to admin_frontend_view_editor_path(view), class: 'new-menu', title: t('keppler.actions.edit') do
        %span
          = view.format_result
    %td.hidden-xs.hidden-sm
      = link_to admin_frontend_view_editor_path(view), class: 'new-menu', title: t('keppler.actions.edit') do
        %span
          = view.path
    %td{ style: 'width: 15px;padding-right:15px;' }
      %a.action-btn.pull-right{:id => "menu-#{view.id}", 'aria-expanded': 'false', 'aria-haspopup': 'true', 'data-toggle': 'dropdown' }
        %i.icon-options-vertical
      %ul.actions.dropdown-menu{ 'aria-labelledby': "menu-#{view.id}" }
        - if can?(KepplerFrontend::View).index?
          %li
            = link_to admin_frontend_view_path(view), class: 'new-menu', title: t('keppler.actions.show') do
              %i.icon-eye
              = t('keppler.actions.show')
        - if can?(KepplerFrontend::View).update?
          %li
            = link_to edit_admin_frontend_view_path(view), class: 'new-menu', title: t('keppler.actions.edit') do
              %i.icon-pencil
              = t('keppler.actions.edit')
        - if can?(KepplerFrontend::View).editor?
          %li
            = link_to admin_frontend_view_editor_path(view), class: 'new-menu', title: t('keppler.actions.editor') do
              %i.icon-screen-desktop
              = t('keppler.actions.editor')
        - if can?(KepplerFrontend::View).destroy?
          %li
            = link_to admin_frontend_view_path(view), class: 'new-menu', title: t('keppler.actions.delete'), method: :delete, data: { confirm: t('keppler.messages.data_confirm') } do
              %i.icon-trash
              = t('keppler.actions.delete')

rockets/keppler_frontend/app/views/keppler_frontend/admin/views/_view_callback_fields_edit.html.haml
.nested-fields.row{id: "callback-#{f.object.id}"}
  .col-lg-3
    = f.input :function_type, label: t('keppler_frontend.attributes.function'), collection: f.object.set_function_types.map { |v| [v.to_s.split('_').map(&:capitalize).join(" "), v] } , include_blank: false, disabled: true
  .col-lg-4
    = f.input :name, label: t('keppler_frontend.attributes.callback'), collection: f.object.set_callbacks, include_blank: false, disabled: true
  .col-lg-2
    = link_to admin_frontend_view_destroy_callback_path(@view.id, f.object.id.to_i), class: "btn btn-default btn-delete-field" , remote: true, method: :delete, data: { confirm: t('keppler.messages.data_confirm') } do
      %i.icon-trash

rockets/keppler_frontend/app/views/keppler_frontend/admin/views/destroy_callback.js.erb
var formId = $("#callback-<%= @callback.id %> select")[0].id.split('_')[4]

$("#view_view_callbacks_attributes_"+formId+"_id").remove();
$("#callback-<%= @callback.id %>").remove();
$(".spinner").css('display', 'none');

rockets/keppler_frontend/app/views/keppler_frontend/admin/views/edit.html.haml
= render 'form'

rockets/keppler_frontend/app/views/keppler_frontend/admin/views/editor.html.haml
.container
  - if @view.format_result.eql?('HTML')
    = render "keppler_frontend/admin/views/editors/html_editor"
  - if @view.format_result.eql?('Action')
    = render "keppler_frontend/admin/views/editors/only_action"
  - if @view.format_result.eql?('JS')
    = render "keppler_frontend/admin/views/editors/view_js_editor"

rockets/keppler_frontend/app/views/keppler_frontend/admin/views/index.html.haml
#index-container{ :controller => "views" }
  .container
    .row
      .listing.col-lg-12.col-xs-12
        %section.content-header.index-header
          %h1{ style: 'display: inline-block' }
            = t("keppler_frontend.modules.#{controller_path.underscore}")
          = entries(@total, @objects)
        %section.content-actions
          .toolbar
            .toolbar-item
              = link_to reload_admin_frontend_views_path, class: "tool-btn", remote: true do
                %i.icon-reload
            .toolbar-item
              %a.tool-btn{"data-confirm" => "¿Estás seguro?", "data-method" => "delete", "v-bind:href" => "link", :rel => "nofollow", ":class" => "{disabled: !checks}" }
                %i.icon-trash
          - if can?(KepplerFrontend::View).create?
            .add
              = link_to new_admin_frontend_view_path, class: 'btn-add' do
                +
                = t('keppler.actions.add')

        .box.slice-box
          .box-body.no-padding
            %table.table
              %thead
                - if @objects.size.zero?
                  %tr
                    %th.not-records.center
                      %h6= t('keppler.messages.not_found_records', model:  t("keppler_frontend.models.pluralize.views"))

                - else
                  %tr
                    %th
                      - if can?(KepplerFrontend::View).destroy_multiple?
                        .item-check
                          .checkbox
                            %label{ for: 'checkbox-all' }
                              %input{ type: 'checkbox', id: 'checkbox-all', '@click' => 'selectAll()' }
                              %span.cr
                                %i.cr-icon.glyphicon.glyphicon-ok
                    %th.hidden-xs.hidden-sm
                      = sort_link(@q, :method) do
                        = t('activerecord.attributes.method')
                    %th.hidden-xs
                      = sort_link(@q, :name) do
                        = t('activerecord.attributes.name')
                    %th.hidden-xs
                      = sort_link(@q, :url) do
                        = t('activerecord.attributes.url')
                    %th.hidden-xs.hidden-sm
                      = sort_link(@q, :active) do
                        = t('activerecord.attributes.active')
                    %th.hidden-xs.hidden-sm
                      = sort_link(@q, :format_result) do
                        = t('activerecord.attributes.format_result')
                    %th.hidden-xs.hidden-sm
                      = sort_link(@q, :path) do
                        = t('activerecord.attributes.path')
                    %th
                    %th
              %tbody.objects-container
                = render 'admin/layouts/listing_preloader'
                = render 'listing', objects: @objects
        %center#paginator-module
          = paginate @objects, window: 1
  %aside.control-sidebar
    = render "description"

:javascript
  $(document).ready(function(){
    $('#view').click(function() {
      $('#upload_file_view').click()
      $('#upload_file_view').change(function() {
        $('.waiting').css('display', 'block')
        $('#upload_form_view').submit()
      })
    });

    renderImg();
  });

rockets/keppler_frontend/app/views/keppler_frontend/admin/views/new.html.haml
= render 'form'

rockets/keppler_frontend/app/views/keppler_frontend/admin/views/reload.js.haml
$('#objects-container').html("#{j render 'listing', objects: @objects}");
$('#objects-container').css('opacity', '0');
$('#spinner2').css('display', 'block');
var request = $.ajax({url: "/admin/views", method: "get", dataType: "html"});
request.done(function(msg){$('#spinner2').css('display', 'none');$('#objects-container').css('opacity', '1');});

rockets/keppler_frontend/app/views/keppler_frontend/admin/views/show.html.haml
.container
  .row
    .col-lg-2
      = link_to admin_frontend_views_path, "data-position" => "bottom", "data-tooltip" => t("keppler.actions.back") do
        .arrow-back.btn.btn-default
          %i.fa.fa-angle-left
          = t('keppler.actions.back')

  .show-section
    .row
      .col-lg-12
        .box.slice-box.p-15
          .box-header.with-border
            %h3.box-title= t("keppler.modules.#{controller_path.underscore}")
            .box-tools.pull-right
              - if can?(KepplerFrontend::View).update?
                = link_to edit_admin_frontend_view_path(@view), class: "btn btn-box-tool", title: "#{t('keppler.actions.edit') }" do
                  %i.icon-pencil
              - if can?(KepplerFrontend::View).destroy?
                = link_to admin_frontend_view_path(@view), class: "btn btn-box-tool", title: "#{t('keppler.actions.delete')}", method: :delete, data: { confirm: t('keppler.messages.data_confirm') } do
                  %i.icon-trash
          .box-body.box-body-no-padding
            %table.table
              %tbody
                - @view.as_json(only: ["name", "url", "method", "active", "format_result", "position", "deleted_at"]).each do |attribute, value|
                  - unless attribute.eql?('position') || attribute.eql?('deleted_at')
                    %tr.list-row
                      %th.display-label= t("activerecord.attributes.#{attribute}")
                      %td.display-value.fs-body-1.tc-black-2
                        - if @attachments.include?(attribute)
                          = image_tag value.url unless value.url.blank?
                        - else
                          = value.blank? ? '-----------' : value