rockets/keppler_frontend/config/routes.rb
KepplerFrontend::Engine.routes.draw do
  get '/', to: 'app/frontend#index', as: :index
  root to: 'app/frontend#keppler', as: :keppler
  namespace :admin do
    scope :frontend, as: :frontend do
      resources :parameters do
        get '(page/:page)', action: :index, on: :collection, as: ''
        get '/clone', action: 'clone'
        post '/sort', action: :sort, on: :collection
        post '/upload', action: 'upload', as: 'upload'
        get '/download', action: 'download', as: 'download'
        get(
          '/reload',
          action: :reload,
          on: :collection,
        )
        delete(
          '/destroy_multiple',
          action: :destroy_multiple,
          on: :collection,
          as: :destroy_multiple
        )
      end

      resources :functions do
        get '(page/:page)', action: :index, on: :collection, as: ''
        get '/clone', action: 'clone'
        post '/sort', action: :sort, on: :collection
        post '/upload', action: 'upload', as: 'upload'
        get '/download', action: 'download', as: 'download'
        get '/editor', action: 'editor'
        post '/editor/save', action: 'editor_save'
        delete '/destroy_param/:param_id', action: :destroy_param, as: :destroy_param
        get(
          '/reload',
          action: :reload,
          on: :collection,
        )
        delete(
          '/destroy_multiple',
          action: :destroy_multiple,
          on: :collection,
          as: :destroy_multiple
        )
      end

      resources :callback_functions do
        get '(page/:page)', action: :index, on: :collection, as: ''
        get '/clone', action: 'clone'
        post '/sort', action: :sort, on: :collection
        post '/upload', action: 'upload', as: 'upload'
        get '/download', action: 'download', as: 'download'
        get '/editor', action: 'editor'
        post '/editor/save', action: 'editor_save'
        get(
          '/reload',
          action: :reload,
          on: :collection,
        )
        delete(
          '/destroy_multiple',
          action: :destroy_multiple,
          on: :collection,
          as: :destroy_multiple
        )
      end

      resources :partials do
        get '(page/:page)', action: :index, on: :collection, as: ''
        get '/clone', action: 'clone'
        post '/sort', action: :sort, on: :collection
        post '/upload', action: 'upload', as: 'upload'
        post '/editor/save', action: 'editor_save'
        get '/download', action: 'download', as: 'download'
        get(
          '/reload',
          action: :reload,
          on: :collection,
        )
        delete(
          '/destroy_multiple',
          action: :destroy_multiple,
          on: :collection,
          as: :destroy_multiple
        )
      end

      resources :themes do
        get '(page/:page)', action: :index, on: :collection, as: ''
        get '/clone', action: 'clone'
        post '/sort', action: :sort, on: :collection
        post '/upload', action: 'upload', as: 'upload'
        get '/download', action: 'download', as: 'download'
        get '/show_covers', action: 'show_covers', as: 'show_covers'
        get '/editor', action: 'editor'
        post '/editor/save', action: 'editor_save'
        get(
          '/reload',
          action: :reload,
          on: :collection,
        )
        delete(
          '/destroy_multiple',
          action: :destroy_multiple,
          on: :collection,
          as: :destroy_multiple
        )
      end

      get '/assets', to: 'multimedia#index', as: 'multimedia'
      post '/assets/upload', to: 'multimedia#upload', as: 'upload_multimedia'
      get '/assets/upload', to: 'multimedia#upload', as: 'show_upload_multimedia'
      delete '/assets/:search/:fileformat', to: 'multimedia#destroy', as: 'destroy_multimedia'
      get '/assets/:search/:fileformat', to: 'multimedia#destroy', as: 'show_destroy_multimedia'

      resources :views do
        delete '/destroy_callback/:view_callback_id', action: :destroy_callback, as: :destroy_callback
        get '(page/:page)', action: :index, on: :collection, as: ''
        get '/clone', action: 'clone'
        get '/editor', action: 'editor'
        post '/editor/save', action: 'editor_save'
        post '/live_editor/save', action: 'live_editor_save'
        post '/sort', action: :sort, on: :collection
        post '/select_theme_view/:theme_view', action: 'select_theme_view', as: :select_theme

        get(
          '/reload',
          action: :reload,
          on: :collection,
        )
        delete(
          '/destroy_multiple',
          action: :destroy_multiple,
          on: :collection,
          as: :destroy_multiple
        )
      end

    end
  end
end

rockets/keppler_frontend/app/controllers/keppler_frontend/admin/multimedia_controller.rb
require_dependency "keppler_frontend/application_controller"
module KepplerFrontend
  module Admin
    # ViewsController
    class MultimediaController < ApplicationController
      layout 'keppler_frontend/admin/layouts/application'
      before_action :authorization
      before_action :set_filesystem      
      before_action :only_development
      skip_before_action :verify_authenticity_token, only: :upload

      def index
        set_data(@filesystem)
        flash[:notice] = [nil, 'images', 'success']
      end

      def upload
        uploader = ImgFileUploader.new
        tab = "images"
        message = "fail"
        unless params[:view].nil?
          fotmat_valid = @filesystem .validate_format(params[:view][:file].original_filename)
          message = "success"
          if fotmat_valid
            File.open(params[:view][:file].path) do |file|
              uploader.store!(file)
              @filesystem .move_and_rename_file(uploader, params[:view][:file])
            end
            filename = params[:view][:file].original_filename
            tab = select_tab(fotmat_valid, filename)
          else
            tab = "images"
            message = "fail"
          end
        end
        set_data(@filesystem )
        flash[:notice] = [ t("keppler_frontend.#{message}"), tab, message ]
        render :index
      end

      def destroy
        file = @filesystem .search_with_format(params[:search], params[:fileformat])[0]
        unless file.nil?
          fotmat_valid = @filesystem .validate_format(file[:name])
          tab = select_tab(fotmat_valid, file[:name])
          [:cover_url, :url].each { |atr| File.delete(file[atr]) if File.exist?(file[atr]) }
        else
          tab = select_tab_by_format(params[:fileformat])
        end
        set_data(@filesystem)
        flash[:notice] = [ t("keppler_frontend.destroy"), tab, "success" ]
        render :index
      end

      private

      def authorization
        authorize View
      end

      def set_filesystem
        @filesystem  = FileUploadSystem.new
      end

      def set_data(filesystem )
        @view = View.new
        @files_list = filesystem .files_list
      end

      def select_tab(fotmat_valid, file)
        return nil unless fotmat_valid
        @filesystem  = FileUploadSystem.new
        file = @filesystem .file_object(file)
        file[:folder]
      end

      def select_tab_by_format(content_type)
        filesystem  = FileUploadSystem.new
        file = filesystem .select_folder_by_format(content_type)
      end
    end
  end
end

rockets/keppler_frontend/app/views/keppler_frontend/admin/multimedia/index.html.haml
.row
  .col-lg-12
    .container-files
      %h1 Assets
      = simple_form_for @view, url: admin_frontend_upload_multimedia_path, method: :post do |f|
        = f.input :file, as: :file, label: false
        - if flash[:notice]
          .keppler-frontend-message{class: "#{ flash[:notice].last.eql?('success') ? 'text-green' : 'text-red' }"}
            = flash[:notice].first
        .pull-right
          = f.button :submit, t('keppler.permissions.upload'), class: 'btn-primary'
  .col-lg-12
    .container-files
      #file-listing
        .nav-tabs-custom
          %ul.nav.nav-tabs
            %li{ class: "#{'active' if flash[:notice].second.eql?('images') }"}
              %a{'aria-expanded': "true", "data-toggle" => "tab", :href => "#tab_1"}
                %i.fa.fa-image
                %span.hidden-xs
                  Images
            %li{ class: "#{'active' if flash[:notice].second.eql?('videos') }"}
              %a{'aria-expanded': 'false', "data-toggle" => "tab", :href => "#tab_2"}
                %i.fa.fa-film
                %span.hidden-xs
                  Videos
            %li{ class: "#{'active' if flash[:notice].second.eql?('audios') }"}
              %a{'aria-expanded': 'false', "data-toggle" => "tab", :href => "#tab_3"}
                %i.fa.fa-music
                %span.hidden-xs
                  Audios
            %li{ class: "#{'active' if flash[:notice].second.eql?('fonts') }"}
              %a{'aria-expanded': 'false', "data-toggle" => "tab", :href => "#tab_4"}
                %i.fa.fa-text-height
                %span.hidden-xs
                  Fonts
            %li{ class: "#{'active' if flash[:notice].second.eql?('html') }"}
              %a{'aria-expanded': 'false', "data-toggle" => "tab", :href => "#tab_5"}
                %i.fa.fa-code
                %span.hidden-xs
                  Components
            %li{ class: "#{'active' if flash[:notice].second.eql?('javascripts') }"}
              %a{'aria-expanded': 'false', "data-toggle" => "tab", :href => "#tab_6"}
                %i.fa.fa-magic
                %span.hidden-xs
                  Javascripts
            %li{ class: "#{'active' if flash[:notice].second.eql?('stylesheets') }"}
              %a{'aria-expanded': 'false', "data-toggle" => "tab", :href => "#tab_7"}
                %i.fa.fa-paint-brush
                %span.hidden-xs
                  Stylesheets
          .tab-content
            #tab_1.tab-pane.bg-gray{ class: "#{'active' if flash[:notice].second.eql?('images') }"}
              .row
                - @files_list.each_with_index do |file, i|
                  - if file[:folder].eql?("images")
                    .col-lg-4
                      .box.box-solid
                        .box-header.with-border{title: "#{file[:name]}"}
                          .row
                            .col-lg-10
                              %h4.box-title
                                %i.fa.fa-image
                                = truncate(file[:name], length: 40, omission: '...')
                            .col-lg-2
                              = link_to admin_frontend_destroy_multimedia_path(file[:search], file[:format]), method: :delete, data: { confirm: t('keppler.messages.data_confirm') } do
                                %i.fa.fa-trash
                        .box-body.no-padding
                          .back-file
                            .file-image{style:"background-image:url('#{file[:path]}')"}
                        .box-body
                          %span.box-title
                            = file[:size]
                            %button.btn.btn-default.pull-right{onclick: "copy('#{file[:id]}')"}
                              %input.hidden{id: "#{file[:id]}", value: "#{file[:path]}"}
                              %i.fa.fa-save
                              = t('keppler.keppler_frontend.multimedia.copy')
            #tab_2.tab-pane.bg-gray{ class: "#{'active' if flash[:notice].second.eql?('videos') }"}
              .row
                - @files_list.each_with_index do |file, i|
                  - if file[:folder].eql?("videos")
                    .col-lg-4
                      .box.box-solid
                        .box-header.with-border{title: "#{file[:name]}"}
                          .row
                            .col-lg-10
                              %h4.box-title
                                %i.fa.fa-film
                                = truncate(file[:name], length: 40, omission: '...')
                            .col-lg-2
                              = link_to admin_frontend_destroy_multimedia_path(file[:search], file[:format]), method: :delete , data: { confirm: t('keppler.messages.data_confirm') } do
                                %i.fa.fa-trash
                        .box-body.no-padding
                          .back-file
                            .center
                              %video{ controls: 'true'}
                                %source{ src:"#{file[:path]}", type:"video/#{file[:format]}" }
                                Su navegador no soporta contenido multimedia.
                        .box-body
                          %span.box-title
                            = file[:size]
                            %button.btn.btn-default.pull-right{onclick: "copy('#{file[:id]}')"}
                              %input.hidden{id: "#{file[:id]}", value: "#{file[:path]}"}
                              %i.fa.fa-save
                              = t('keppler.keppler_frontend.multimedia.copy')
            #tab_3.tab-pane.bg-gray{ class: "#{'active' if flash[:notice].second.eql?('audios') }"}
              .row
                - @files_list.each_with_index do |file, i|
                  - if file[:folder].eql?("audios")
                    .col-lg-4
                      .box.box-solid
                        .box-header.with-border{title: "#{file[:name]}"}
                          .row
                            .col-lg-10
                              %h4.box-title
                                %i.fa.fa-music
                                = truncate(file[:name], length: 40, omission: '...')
                            .col-lg-2
                              = link_to admin_frontend_destroy_multimedia_path(file[:search], file[:format]), method: :delete , data: { confirm: t('keppler.messages.data_confirm') } do
                                %i.fa.fa-trash
                        .box-body.no-padding
                          .back-file
                            .center
                              %audio{controls: true}
                                %source{ src:"#{file[:path]}", type:"audio/#{file[:format]}" }
                                Your browser does not support the audio tag.
                        .box-body
                          %span.box-title
                            = file[:size]
                            %button.btn.btn-default.pull-right{onclick: "copy('#{file[:id]}')"}
                              %input.hidden{id: "#{file[:id]}", value: "#{file[:path]}"}
                              %i.fa.fa-save
                              = t('keppler.keppler_frontend.multimedia.copy')
            #tab_4.tab-pane.bg-gray{ class: "#{'active' if flash[:notice].second.eql?('fonts') }"}
              .row
                - @files_list.each_with_index do |file, i|
                  - if file[:folder].eql?("fonts")
                    .col-lg-3
                      .box.box-solid
                        .box-header.with-border{title: "#{file[:name]}"}
                          .row
                            .col-lg-10
                              %h4.box-title
                                %i.fa.fa-text-height
                                = truncate(file[:name], length: 35, omission: '...')
                            .col-lg-2
                              = link_to admin_frontend_destroy_multimedia_path(file[:search], file[:format]), method: :delete, data: { confirm: t('keppler.messages.data_confirm') }  do
                                %i.fa.fa-trash
                        .box-body.no-padding
                          .back-file
                            .center
                              %i.fa.fa-text-height#font-icon-size
                        .box-body
                          %span.box-title
                            = file[:size]
                            %button.btn.btn-default.pull-right{onclick: "copy('#{file[:id]}')"}
                              %input.hidden{id: "#{file[:id]}", value: "#{file[:path]}"}
                              %i.fa.fa-save
                              = t('keppler.keppler_frontend.multimedia.copy')

            #tab_5.tab-pane.bg-gray{ class: "#{'active' if flash[:notice].second.eql?('html') }"}
              .row
                - @files_list.each_with_index do |file, i|
                  - if file[:folder].eql?("html")
                    .col-lg-3
                      .box.box-solid
                        .box-header.with-border{title: "#{file[:name]}"}
                          .row
                            .col-lg-10
                              %h4.box-title
                                %i.fa.fa-code
                                = truncate(file[:name], length: 25, omission: '...')
                            .col-lg-2
                              = link_to admin_frontend_destroy_multimedia_path(file[:search], file[:format]), method: :delete, data: { confirm: t('keppler.messages.data_confirm') }  do
                                %i.fa.fa-trash
                        .box-body.no-padding
                          .back-file
                            .center
                              - if file[:cover].nil?
                                %i.fa.fa-code#font-icon-size
                              - else
                                = image_tag file[:cover], style: "width: 100%"
                        .box-body
                          %span.box-title
                            = file[:size]
                            %button.btn.btn-default.pull-right{onclick: "copyHtml('#{file[:id]}')"}
                              %textarea.hidden{id: "#{file[:id]}", value: "#{file[:html]}"}
                              %i.fa.fa-save
                              = t('keppler.keppler_frontend.multimedia.copy_html')

            #tab_6.tab-pane.bg-gray{ class: "#{'active' if flash[:notice].second.eql?('javascripts') }"}
              .row
                - @files_list.each_with_index do |file, i|
                  - if file[:folder].eql?("javascripts") && !file[:name].eql?("application.js")
                    .col-lg-3
                      .box.box-solid
                        .box-header.with-border{title: "#{file[:name]}"}
                          .row
                            .col-lg-10
                              %h4.box-title
                                %i.fa.fa-magic
                                = truncate(file[:name], length: 35, omission: '...')
                            .col-lg-2
                              = link_to admin_frontend_destroy_multimedia_path(file[:search], file[:format]), method: :delete, data: { confirm: t('keppler.messages.data_confirm') }  do
                                %i.fa.fa-trash
                        .box-body.no-padding
                          .back-file
                            .center
                              %i.fa.fa-magic#font-icon-size
                        .box-body
                          %span.box-title
                            = file[:size]
                            %button.btn.btn-default.pull-right{onclick: "copy('#{file[:id]}')"}
                              %input.hidden{id: "#{file[:id]}", value: "#{file[:path]}"}
                              %i.fa.fa-save
                              = t('keppler.keppler_frontend.multimedia.copy')
            #tab_7.tab-pane.bg-gray{ class: "#{'active' if flash[:notice].second.eql?('stylesheets') }"}
              .row
                - @files_list.each_with_index do |file, i|
                  - if file[:folder].eql?("stylesheets") && !file[:name].eql?("application.scss")
                    .col-lg-3
                      .box.box-solid
                        .box-header.with-border{title: "#{file[:name]}"}
                          .row
                            .col-lg-10
                              %h4.box-title
                                %i.fa.fa-paint-brush
                                = truncate(file[:name], length: 35, omission: '...')
                            .col-lg-2
                              = link_to admin_frontend_destroy_multimedia_path(file[:search], file[:format]), method: :delete, data: { confirm: t('keppler.messages.data_confirm') }  do
                                %i.fa.fa-trash
                        .box-body.no-padding
                          .back-file
                            .center
                              %i.fa.fa-paint-brush#font-icon-size
                        .box-body
                          %span.box-title
                            = file[:size]
                            %button.btn.btn-default.pull-right{onclick: "copy('#{file[:id]}')"}
                              %input.hidden{id: "#{file[:id]}", value: "#{file[:path]}"}
                              %i.fa.fa-save
                              = t('keppler.keppler_frontend.multimedia.copy')